local test = require("tests/harness")

return section("block", function()
	describe("parsing", function()
		it("parses B and BLOCK properly", function()
			test.must("B 0")
			test.must("BLOCK 0")
		end)
	end)

	describe("functions", function()
		it("should be usable as the sole argument to :", function()
			test.must(": BLOCK QUIT 1")
		end)
		it("should be usable as the sole argument to BLOCK", function()
			test.must("BLOCK BLOCK QUIT 1")
		end)
		it("should be usable as the sole argument to CALL", function()
			test.assert("3", "CALL BLOCK + 1 2")
			test.assert("7", "; = bar BLOCK + 4 foo ; = foo 3 : CALL bar")
		end)
		it("should be usable as the sole argument to ,", function()
			test.must(", BLOCK QUIT 1")
		end)
		it("should be usable as the rhs argument to =", function()
			test.must("= foo BLOCK QUIT 1")
		end)
		it("should be usable as the rhs argument to &", function()
			test.must("& TRUE BLOCK QUIT 1")
		end)
		it("should be usable as the rhs argument to |", function()
			test.must("| FALSE BLOCK QUIT 1")
		end)
		it("should be usable as either argument to ;", function()
			test.must("; 12 BLOCK QUIT 1")
			test.must("; BLOCK QUIT 1 12")
		end)
		it("should be usable as the second and third arguments to IF", function()
			test.must("IF TRUE  BLOCK QUIT 1 NULL")
			test.must("IF FALSE BLOCK QUIT 1 NULL")
		end)
		it("should be usable as the second argument of WHILE", function()
			test.must("WHILE FALSE BLOCK QUIT 1")
			test.must("; = i TRUE : WHILE i ; = i FALSE : BLOCK QUIT 1")
		end)
	end)
end)
