local test = require("tests/harness")

return section("boolean", function()
	describe("parsing", function()
		it("parses F and FALSE as false", function()
			test.assert("false", "F")
			test.assert("false", "FALSE")
		end)
		it("parses T and TRUE as true", function()
			test.assert("true", "T")
			test.assert("true", "TRUE")
		end)
	end)

	describe("conversions", function()
		describe("integer", function()
			it("converts false to zero", function()
				test.assert("0", "+ 0 FALSE")
			end)
			it("converts true to one", function()
				test.assert("1", "+ 0 TRUE")
			end)
		end)
		describe("string", function()
			it("converts false to the string 'false'", function()
				test.assert("false", "+ '' FALSE")
			end)
			it("converts true to the string 'true'", function()
				test.assert("true", "+ '' TRUE")
			end)
		end)
		describe("boolean", function()
			it("simply returns itself", function()
				test.assert("false", "!!FALSE")
				test.assert("true", "!!TRUE")
			end)
		end)
	end)
end)
