local test = require("tests/harness")

return section("null", function()
	describe("parsing", function()
		it("parses N and NULL as null", function()
			test.assert("null", "N")
			test.assert("null", "NULL")
		end)
	end)
	describe("conversions", function()
		describe("integer", function()
			it("converts to zero", function()
				test.assert("0", "+ 0 NULL")
			end)
		end)
		describe("string", function()
			it("converts to an empty string", function()
				test.assert("", "+ '' NULL")
				test.assert("x", "+ 'x' NULL")
			end)
		end)
		describe("boolean", function()
			it("converts to false", function()
				test.assert("false", "!!NULL")
			end)
		end)
		describe("list", function()
			it("converts to an empty list", function()
				test.assert("[]", "+ @ NULL")
			end)
		end)
	end)
end)
