local test = require("tests/harness")

return section("AND", function()
	describe("when the lhs is falsey", function()
		it("returns the lhs", function()
			test.assert("0", "& 0 QUIT 1")
			test.assert("false", "& FALSE QUIT 1")
			test.assert("", "& '' QUIT 1")
			test.assert("null", "& NULL QUIT 1")
			test.assert("[]", "& @ QUIT 1")
		end)
	end)

	describe("when the lhs is truthy", function()
		it("executes and returns the rhs", function()
			test.assert("1", "; & 1 (= a 1) a")
			test.assert("2", "; & TRUE (= a 2) a")
			test.assert("3", "; & 'hi' (= a 3) a")
			test.assert("4", "; & '0' (= a 4) a")
			test.assert("5", "; & 'NaN' (= a 5) a")
			test.assert("[]", "; & ,@ (= a @) a")
		end)
	end)

	describe("when the rhs is a block", function()
		it("accepts blocks as the second operand", function()
			test.assert("3", "; = a 3 : CALL & 1 BLOCK a")
			test.assert("5", "; = a 3 : CALL & 1 BLOCK + a 2")
		end)
	end)

	it("does not accept BLOCK values for the first arg", function()
		test.refute("& (BLOCK a) 1")
		test.refute("& (BLOCK QUIT 0) 1")
	end)

	it("requires exactly two arguments", function()
		test.refute("&")
		test.refute("& 1")
		test.must("& 1 1")
	end)
end)
