local test = require("tests/harness")

return section("GREATER-THAN", function()
	describe("when the first arg is a boolean", function()
		it("is only true when TRUTHY and the rhs is falsey", function()
			test.assert("true", "> TRUE FALSE")
			test.assert("true", "> TRUE 0")
			test.assert("true", "> TRUE ''")
			test.assert("true", "> TRUE NULL")
			test.assert("true", "> TRUE @")
		end)

		it("is false all other times", function()
			test.assert("false", "> TRUE TRUE")
			test.assert("false", "> TRUE 1")
			test.assert("false", "> TRUE '1'")
			test.assert("false", "> TRUE ,1")
			test.assert("false", "> FALSE ~1")
			test.assert("false", "> FALSE TRUE")
			test.assert("false", "> FALSE FALSE")
			test.assert("false", "> FALSE 1")
			test.assert("false", "> FALSE '1'")
			test.assert("false", "> FALSE 0")
			test.assert("false", "> FALSE ''")
			test.assert("false", "> FALSE NULL")
			test.assert("false", "> FALSE @")
		end)
	end)

	describe("when the first arg is a string", function()
		it("performs lexicographical comparison", function()
			test.assert("false", "> 'a' 'aa'")
			test.assert("true", "> 'b' 'aa'")
			test.assert("true", "> 'aa' 'a'")
			test.assert("false", "> 'aa' 'b'")
			test.assert("false", "> 'A' 'AA'")
			test.assert("true", "> 'B' 'AA'")
			test.assert("true", "> 'AA' 'A'")
			test.assert("false", "> 'AA' 'B'")
			test.assert("true", "> 'a' 'A'")
			test.assert("false", "> 'A' 'a'")
			test.assert("true", "> 'z' 'Z'")
			test.assert("false", "> 'Z' 'z'")
			test.assert("true", "> ':' '9'")
			test.assert("true", "> '1' '0'")
		end)

		it("performs it even with integers", function()
			test.assert("false", "> '0' '00'")
			test.assert("false", "> '1' '12'")
			test.assert("false", "> '100' '12'")
			test.assert("true", "> '00' '0'")
			test.assert("true", "> '12' '1'")
			test.assert("true", "> '12' '100'")
		end)
	end)
end)
