local test = require("tests/harness")

return section("OR", function()
	it("returns the lhs if its truthy", function()
		test.assert("1", "| 1 QUIT 1")
		test.assert("2", "| 2 QUIT 1")
		test.assert("true", "| TRUE QUIT 1")
		test.assert("hi", "| 'hi' QUIT 1")
		test.assert("0", "| '0' QUIT 1")
		test.assert("NaN", "| 'NaN' QUIT 1")
		test.assert("[1]", "| ,1 QUIT 1")
	end)

	it("executes the rhs only if the lhs is falsey", function()
		test.assert("1", "; | 0 (= a 1) a")
		test.assert("2", "; | FALSE (= a 2) a")
		test.assert("3", "; | NULL (= a 3) a")
		test.assert("4", "; | '' (= a 4) a")
		test.assert("5", "; | @ (= a 5) a")
	end)

	it("accepts blocks as the second operand", function()
		test.assert("3", "; = a 3 : CALL | 0 BLOCK a")
		test.assert("5", "; = a 3 : CALL | 0 BLOCK + a 2")
	end)

	it("does not accept BLOCK values for the first arg", function()
		test.refute("; = a 3 : | (BLOCK a) 1")
		test.refute("| (BLOCK QUIT 0) 1")
	end)

	it("requires exactly two arguments", function()
		test.refute("|")
		test.refute("| 1")
		test.must("| 1 1")
	end)
end)
