local test = require("tests/harness")

return section("[", function()
	it("gets the first element of lists", function()
		test.assert("1", "[ ,1")
		test.assert("1", "[ +,1 ,2")
		test.assert("1", "[ +@123")
		test.assert("1", "[ *,1 4")
	end)

	it("gets the first character of strings", function()
		test.assert("a", "[ 'a'")
		test.assert("a", "[ 'abc'")
		test.assert("a", "[ +'abc' 'def'")
		test.assert("a", "[ +'' 'abc'")
		test.assert("a", "[ *'abc' 3")
	end)

	it("only allows a string or list as the first operand (invalid types)", function()
		test.refute("[ 123")
		test.refute("[ TRUE")
		test.refute("[ FALSE")
		test.refute("[ NULL")
	end)

	it("does not take head on empty lists or strings (empty list)", function()
		test.refute("[ @")
		-- test.refute('[ ""')
	end)

	it("does not allow a block (strict types)", function()
		test.refute('; = a ,"a" : [ (BLOCK a)')
		test.refute("; = a (BLOCK QUIT 0) : [ a")
	end)

	it("requires exactly one argument (argument count)", function()
		test.refute("[")
		test.must("[ 'a'")
	end)
end)
