local test = require("tests/harness")

return section("~", function()
	it("negates its argument", function()
		test.assert("-1", "~ 1")
		test.assert("-10", "~ 10")
		test.assert("12", "~ ~12")
		test.assert("123", "~ (- 0 123)")
		test.assert("0", "~0")
	end)

	it("converts its argument to an integer", function()
		test.assert("-2", '~ "2"')
		test.assert("-45", '~ "45"')
		test.assert("-1", "~ TRUE")
		test.assert("0", "~ FALSE")
		test.assert("0", "~ NULL")
		test.assert("-3", "~ +@999")
	end)

	it("requires exactly one argument (argument count)", function()
		test.refute("~")
		test.must("~ 1")
	end)

	it("does not allow blocks as the first operand (strict types)", function()
		test.refute("; = a 0 : ~ BLOCK a")
		test.refute("~ BLOCK QUIT 0")
	end)
end)
