local test = require("tests/harness")

return section("!", function()
	it("inverts its argument", function()
		test.assert("true", "! FALSE")
		test.assert("false", "! TRUE")
	end)

	it("converts its argument to a boolean", function()
		test.assert("true", '! ""')
		test.assert("false", '! "0"')
		test.assert("false", '! "1"')
		test.assert("true", "! NULL")
		test.assert("true", "! 0")
		test.assert("false", "! 1")
		test.assert("true", "! @")
		test.assert("false", "! ,@")
	end)

	it("requires exactly one argument (argument count)", function()
		test.refute("!")
		test.must("! TRUE")
	end)

	it("does not allow blocks as the first operand (strict types)", function()
		test.refute("; = a 0 : ! BLOCK a")
		test.refute("! BLOCK QUIT 0")
	end)
end)
