local test = require("tests/harness")

return section("QUIT", function()
	it("must quit the process with the given return value", function()
		test.todo("QUIT 0 -- expect exit code 0")
		test.todo("QUIT 1 -- expect exit code 1")
		test.todo("QUIT 2 -- expect exit code 2")
		test.todo("QUIT 10 -- expect exit code 10")
		test.todo("QUIT 49 -- expect exit code 49")
		test.todo("QUIT 123 -- expect exit code 123")
		test.todo("QUIT 126 -- expect exit code 126")
		test.todo("QUIT 127 -- expect exit code 127")
	end)

	it("must convert to an integer", function()
		test.todo('QUIT "12" -- expect exit code 12')
		test.todo("QUIT TRUE -- expect exit code 1")
		test.todo("QUIT FALSE -- expect exit code 0")
		test.todo("QUIT NULL -- expect exit code 0")
		test.todo("QUIT @ -- expect exit code 0")
		test.todo("QUIT ,123 -- expect exit code 1")
	end)

	it("requires exactly one argument (argument count)", function()
		test.refute("QUIT")
		test.must("QUIT 0")
	end)

	it("does not allow blocks as the first operand (strict types)", function()
		test.refute("; = a 0 : QUIT BLOCK a")
		test.refute("QUIT BLOCK QUIT 0")
	end)
end)
