local test = require("tests/harness")

return section("FUNCTIONS", function()
	it("parses trailing word function letters", function()
		test.must("L 1")
		test.must("RAND")
		test.must("RANDOM")
		test.must("RAND_INT")
		test.must("RAND_OM_NUMBER")
		test.must("R___")
	end)

	it("does not parse digits or lower-case letters", function()
		test.assert("1", "L1")
		test.assert("3", "LENGTH123")
		test.assert("1", "; = a 3 : LENa")
		test.assert("2", "; = a 13 : L_a")
		test.assert("4", "; = a 9514 : LENGTH_a")
		test.assert("0", "; = a @ : LE_N_G__TH_a")
		test.assert("0", "; = a @ : LABCDEFGHIJKLMNOPQRSTUVWXYZ_a")
	end)

	it("does not parse trailing tokens for symbolic functions", function()
		test.assert("[]", "+@@")
		test.assert("3true", '++ "" 3 TRUE')
	end)
end)
