local test = require("tests/harness")

return section("STRING", function()
	it("parses empty strings properly", function()
		test.assert("", "''")
		test.assert("", '""')
	end)

	it("parses quotes of the other type", function()
		test.assert('"', "'\"'")
		test.assert("'", '"\'"')
		test.assert("hello 'world'", "\"hello 'world'\"")
		test.assert('hello "world"', "'hello \"world\"'")
	end)

	it("parses normal strings", function()
		test.assert("hello world", '"hello world"')
		test.assert("0", '"0"')
		test.assert(" 1234", '" 1234"')
		test.assert(string.rep("x", 1000), '"' .. string.rep("x", 1000) .. '"')
	end)

	it("does not interpret escape sequences", function()
		test.assert("\\n", "'\\n'")
		test.assert("\\", "'\\'")
		test.assert("hello\\", "'hello\\'")
		test.assert("\\r\\n\\f\\0x45", "'\\r\\n\\f\\0x45'")
	end)
end)
