local test = require("tests/harness")

return section("VARIABLE", function()
	it("parses basic variables properly", function()
		test.assert("3", "= a 3")
		test.assert("3", "= abcd 3")
		test.assert("3", "= abcdefghijklmnopqrstuvwxyz 3")
	end)

	it("parses variables with underscores", function()
		test.assert("3", "= _ 3")
		test.assert("3", "= _________ 3")
		test.assert("3", "= _________hello 3")
		test.assert("3", "= hello___________world 3")
		test.assert("3", "= _h_e_l_l_o__w_o_r_l_d_ 3")
	end)

	it("parses variables with digits", function()
		test.assert("3", "= a0 3")
		test.assert("3", "= a123 3")
		test.assert("3", "= aaa123 3")
		test.assert("3", "= a0aa0a 3")
		test.assert("3", "= a00a0aaaaaa0a 3")
	end)

	it("parses variables with digits and underscores", function()
		test.assert("3", "= _0 3")
		test.assert("3", "= a_0 3")
		test.assert("3", "= a0_ 3")
		test.assert("3", "= a__1_2_3345_a 3")
		test.assert("3", "= _1ab_1_2_3345_ 3")
	end)

	it("does not use upper case letters", function()
		test.assert("true", "= abcTRUE")
	end)

	it("parses the maximum length variable", function()
		test.assert("true", "= " .. string.rep("a", 127) .. " TRUE")
	end)
end)
